const validateFunc =require("./validation_middleware")
module.exports.userRegisterValidation = validateFunc(require("../validation/user.validation"))
module.exports.genderValidation = validateFunc(require("../validation/gender.validation"))
module.exports.userLoginValidation = validateFunc(require("../validation/userLogin.validation"))
module.exports.productCreateValidation = validateFunc(require("../validation/product.validation"))
module.exports.productUpdateValidation = validateFunc(require("../validation/product.update.validation"))
module.exports.categoryCreateValidation = validateFunc(require("../validation/category.validation"))
module.exports.categoryUpdateValidation = validateFunc(require("../validation/category.update.validation"))
module.exports.orderCreateValidation = validateFunc(require("../validation/order.validation"))
module.exports.orderUpdateValidation = validateFunc(require("../validation/order.update.validation"))
module.exports.order_detailCreateValidation = validateFunc(require("../validation/order_detail.validation"))
module.exports.order_detailUpdateValidation = validateFunc(require("../validation/order_detail.update.validation"))
module.exports.sizeCreateValidation = validateFunc(require("../validation/size.validation"))
module.exports.sizeUpdateValidation = validateFunc(require("../validation/size.update.validation"))
module.exports.couponCreateValidation = validateFunc(require("../validation/coupon.validation"))
module.exports.couponUpdateValidation = validateFunc(require("../validation/coupon.update.validation"))
module.exports.pickupOptCreateValidation = validateFunc(require("../validation/pickupOpt.validation"))
module.exports.pickupOptUpdateValidation = validateFunc(require("../validation/pickupOpt.update.validation"))
module.exports.contactCreateValidation = validateFunc(require("../validation/contact.validation"))
module.exports.contactUpdateValidation = validateFunc(require("../validation/contact.update.validation"))
module.exports.paymentCreateValidation = validateFunc(require("../validation/payment.validation"))
module.exports.paymentUpdateValidation = validateFunc(require("../validation/payment.update.validation"))
module.exports.addressCreateValidation = validateFunc(require("../validation/address.validation"))
module.exports.addressUpdateValidation = validateFunc(require("../validation/address.update.validation"))




module.exports.check_credentail=require("./check_credentail")
module.exports.TokenValidation=require("./TokenValidation")